[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
eyre = "0.6.8"
serde = { version = "1.0.143", features = ["derive"] }
hex = "0.4.3"
ssz-rs = { git = "https://github.com/ralexstokes/ssz-rs", rev = "cb08f18ca919cc1b685b861d0fa9e2daabe89737" }
ethers = { version = "1.0.2", features = [ "ws", "default" ] }
thiserror = "1.0.37"
